name: test_expt
random_seed: 4995
model:
  in_features: 15
  linear_layers:
  - 8
  use_batch_norm: true
learning_rate: 0.0001
data:
  feature_path: /Users/johnzhou/research/decision-making/data/synth/sim_features.npy
  label_path: /Users/johnzhou/research/decision-making/data/synth/sim_labels.npy
  train_proportion: 0.8
  train_batch_size: 100
  val_batch_size: 100
trainer:
  gpus: 0
  max_epochs: 100
