name: new_run
random_seed: 4995
model:
  in_features: 3
  linear_layers:
  - 32
  - 8
  - 4
  use_batch_norm: false
learning_rate: 0.0001
data:
  feature_path: /Users/johnzhou/research/decision-making/data/processed/new_run/modeling_features.npy
  label_path: /Users/johnzhou/research/decision-making/data/processed/new_run/modeling_labels.npy
  train_proportion: 0.8
  train_batch_size: 128
  val_batch_size: 128
trainer:
  gpus: 0
  max_epochs: 1000
