name: unbounded_a
random_seed: 4995
model:
  in_features: 19
  linear_layers:
  - 32
  - 8
  - 4
  use_batch_norm: false
learning_rate: 0.0001
data:
  feature_path: /Users/johnzhou/research/decision-making/data/processed/unbounded_a/synth_feats.npy
  label_path: /Users/johnzhou/research/decision-making/data/processed/unbounded_a/synth_labels.npy
  train_proportion: 0.8
  train_batch_size: 64
  val_batch_size: 64
trainer:
  gpus: 0
  max_epochs: 1000
