environment: BlockTask
agent: QLearningAgent
learning_rate: 0.1
epsilon: 0.1
p_reward: null
p_switch: null
transition_probs: null
blocks:
- - LEFT
  - 1.0
  - 30
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 33
- - RIGHT
  - 1.0
  - 30
- - LEFT
  - 1.0
  - 36
- - RIGHT
  - 1.0
  - 30
- - LEFT
  - 1.0
  - 38
- - RIGHT
  - 1.0
  - 31
- - LEFT
  - 1.0
  - 35
- - RIGHT
  - 1.0
  - 25
- - LEFT
  - 1.0
  - 33
- - RIGHT
  - 1.0
  - 36
- - LEFT
  - 1.0
  - 36
- - RIGHT
  - 1.0
  - 32
- - LEFT
  - 1.0
  - 35
- - RIGHT
  - 1.0
  - 25
- - LEFT
  - 1.0
  - 37
- - RIGHT
  - 1.0
  - 34
- - LEFT
  - 1.0
  - 36
- - RIGHT
  - 1.0
  - 35
- - LEFT
  - 1.0
  - 31
- - RIGHT
  - 1.0
  - 43
- - LEFT
  - 1.0
  - 34
- - RIGHT
  - 1.0
  - 35
- - LEFT
  - 1.0
  - 41
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 40
- - RIGHT
  - 1.0
  - 40
- - LEFT
  - 1.0
  - 33
- - RIGHT
  - 1.0
  - 38
- - LEFT
  - 1.0
  - 27
- - RIGHT
  - 1.0
  - 26
- - LEFT
  - 1.0
  - 43
- - RIGHT
  - 1.0
  - 25
- - LEFT
  - 1.0
  - 42
- - RIGHT
  - 1.0
  - 27
- - LEFT
  - 1.0
  - 40
- - RIGHT
  - 1.0
  - 25
- - LEFT
  - 1.0
  - 43
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 28
- - RIGHT
  - 1.0
  - 41
- - LEFT
  - 1.0
  - 44
- - RIGHT
  - 1.0
  - 40
- - LEFT
  - 1.0
  - 43
- - RIGHT
  - 1.0
  - 30
- - LEFT
  - 1.0
  - 27
- - RIGHT
  - 1.0
  - 38
- - LEFT
  - 1.0
  - 34
- - RIGHT
  - 1.0
  - 40
- - LEFT
  - 1.0
  - 28
- - RIGHT
  - 1.0
  - 29
- - LEFT
  - 1.0
  - 44
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 33
- - RIGHT
  - 1.0
  - 39
- - LEFT
  - 1.0
  - 41
- - RIGHT
  - 1.0
  - 41
- - LEFT
  - 1.0
  - 43
- - RIGHT
  - 1.0
  - 29
- - LEFT
  - 1.0
  - 32
- - RIGHT
  - 1.0
  - 29
- - LEFT
  - 1.0
  - 44
- - RIGHT
  - 1.0
  - 42
- - LEFT
  - 1.0
  - 30
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 40
- - RIGHT
  - 1.0
  - 43
- - LEFT
  - 1.0
  - 28
- - RIGHT
  - 1.0
  - 41
- - LEFT
  - 1.0
  - 34
- - RIGHT
  - 1.0
  - 29
- - LEFT
  - 1.0
  - 26
- - RIGHT
  - 1.0
  - 31
- - LEFT
  - 1.0
  - 38
- - RIGHT
  - 1.0
  - 25
- - LEFT
  - 1.0
  - 30
- - RIGHT
  - 1.0
  - 29
- - LEFT
  - 1.0
  - 25
- - RIGHT
  - 1.0
  - 35
- - LEFT
  - 1.0
  - 35
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 35
- - RIGHT
  - 1.0
  - 44
- - LEFT
  - 1.0
  - 41
- - RIGHT
  - 1.0
  - 32
- - LEFT
  - 1.0
  - 40
- - RIGHT
  - 1.0
  - 36
- - LEFT
  - 1.0
  - 39
- - RIGHT
  - 1.0
  - 28
- - LEFT
  - 1.0
  - 25
- - RIGHT
  - 1.0
  - 34
- - LEFT
  - 1.0
  - 39
- - RIGHT
  - 1.0
  - 42
- - LEFT
  - 1.0
  - 43
- - RIGHT
  - 1.0
  - 33
- - LEFT
  - 1.0
  - 35
- - RIGHT
  - 1.0
  - 38
- - LEFT
  - 1.0
  - 30
- - RIGHT
  - 1.0
  - 33
save_location: /Users/johnzhou/research/decision-making/figures
