environment: Block2AFCTask
agent: SwitchingAgent
learning_rate: 0.1
epsilon: 0.05
p_reward: 1.0
p_switch: 0.1
transition_probs:
- - 0.95
  - 0.05
- - 0.05
  - 0.95
blocks:
- - LOW
  - 1.0
  - 100
- - HIGH
  - 1.0
  - 100
- - LOW
  - 1.0
  - 100
- - HIGH
  - 1.0
  - 100
- - LOW
  - 1.0
  - 100
- - HIGH
  - 1.0
  - 100
save_location: /Users/johnzhou/research/decision-making/figures
